[package]
name = "raw-web-sys"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.24"
web-sys = { version = "0.3", features = [ 'Document', 'Element', 'HtmlElement', 'HtmlCollection', 'Node', 'Window', ] }
